Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [6]:
import numpy as np
import pandas as pd

In [5]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [7]:
a1 = a.reshape(4, 3)
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a3 = a.reshape(2, 6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [12]:
a6 = a.reshape(4, -1)
a6

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a8 = a.reshape(2, -1)
a8

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a9 = a.reshape(6, -1)
a9

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a10 = a.reshape(12, -1)
a10

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Строго говоря, он не является одномерным, так как содержит 12 строк.  Хотя он содержит все элементы в одном столбце, он является матрицей с размерностью [12 х 1].  Одномерными же называются массивы линейного вида, а именно множества или последовательности, которые содержат один ряд, список с произвольным количеством элементов.

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
b = np.random.randn(3, 4)
b

array([[ 0.49082253, -0.39524658, -0.43509839, -0.92270184],
       [ 1.27738889,  0.50872344,  0.62913065,  1.3081456 ],
       [-0.11968457, -0.56154514, -0.63233202, -1.35051961]])

In [18]:
c = b.flatten()
c

array([ 0.49082253, -0.39524658, -0.43509839, -0.92270184,  1.27738889,
        0.50872344,  0.62913065,  1.3081456 , -0.11968457, -0.56154514,
       -0.63233202, -1.35051961])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [19]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [20]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a это последовательность.  Питон его выдает как список, list, при итерации в нем индексируются элементы.  Массив b это матрица, Питон выдает его как список в списке, при итерации в нем индексируются и ряд, и столбец, то есть индекс позиции элементов включает два значения.

In [21]:
a[5]

10

In [22]:
b[0, 5]

10

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
c.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [29]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
A_trans = A.T
A_trans

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [34]:
B = np.dot(A, A_trans)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [35]:
B.shape

(4, 4)

In [38]:
C = np.linalg.inv(B)
C

LinAlgError: Singular matrix

In [40]:
x = np.linalg.det(B)
x

0.0

Поскольку определитель матрицы B  равен 0, то нахождение матрицы, обратной B, невозможно.  Обратная матрица находится по формуле:
    B (-1) = (1 / det(B)) * B( * T), где
    B ( * ) - Союзная матрица B, состоящая из алгебраических дополнений матрицы B.

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [41]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [43]:
c = np.random.randint(0, 16, 16)
c

array([ 3,  7,  7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [44]:
C = c.reshape(4, 4)
C

array([[ 3,  7,  7,  2],
       [ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0]])

In [45]:
D = B + (10 * C)
D

array([[ 35,  84,  93,  52],
       [ 64,  90,  96, 192],
       [133, 216, 199, 222],
       [182, 232, 252, 302]])

In [46]:
y = np.linalg.det(D)
y

-23404999.999999978

In [47]:
np.linalg.matrix_rank(D)

4

In [48]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.02745824, -0.02127921, -0.00030506,  0.01848067],
       [-0.00983038, -0.00115445,  0.03006537, -0.01967443],
       [ 0.03091391,  0.00259603, -0.0266755 ,  0.01263576],
       [-0.00169622,  0.01154454, -0.00065371, -0.00325571]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [72]:
G = np.array(D_inv)
for i in range(0, 4):
    for k in range(0, 4):
        if D_inv[i, k] < 0:
            G[i, k] = 0
        else:
            G[i, k] = 1
G

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 0., 0.]])

In [92]:
E = np.where((G == 1), B, C)
E

array([[  3,   7,   7,  32],
       [  5,   4,  86,   7],
       [ 23,  86,   5, 212],
       [ 15, 122,   4,   0]])